language: node_js
node_js:
  - "5.1"
before_install:
  - npm install immutable@3.7.x react@0.14.x react-dom@0.14.x
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - libzmq3-dev
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
    - $HOME/.electron
